In [68]:
import os,numpy as np,pandas as pd,math,matplotlib.pyplot as plt,random 

#=================================FUNCTIONS==========================================

def sigmoid(z):
    return 1 / (1 + math.exp(-z))


vSigmoid = np.vectorize(sigmoid) # functions take a vector and apply sigmoid on each element


def error(Y,A):
        logA = np.log10(A)
        A_1 = 1 - A  # (1-a)
        logA_1 = np.log10(A_1)
        Y_1 = 1 - Y # (1-y)
        
        e =-(np.multiply(Y,logA) + np.multiply(Y_1,logA_1))
        return np.sum(e)/4
    

    

In [81]:
X = np.matrix('0 0; 0 1; 1 0; 1 1')
Y = np.array([0,1,1,0])
X = X.T
m = 4
a = 0.00000000001 # Alpha


# FORWARD PASS

# Layer 0 (Features)

In [45]:


#=========================OUTPUT OF LAYER 0 ============================
#Layer 0 contains our features

A0 = X





# Layer 1

In [46]:

#Number of Nodes 9
#Input of layer 1 is A0 (Output of layer 0)

W1 = np.random.rand(2,2)
b1 = np.random.rand(2,1)


Z1 = np.dot(W1,A0) #Multiping thetas of all nodes of layer 1 with all data instances
Z1 = np.add(Z1,b1) #Broadcasting bais of all nodes of layer 1 
print(Z1.shape)
A1 = np.apply_along_axis(vSigmoid, 0, Z1)  # applying sigmoid on each coloumn 

(2, 4)


# Layer 2

In [47]:
# Number of Nodes 1
#Input of layer 2 is A1 (Output of layer 1)

W2 = np.random.rand(1,2)
b2 = np.random.rand()

Z2 = np.dot(W2,A1) #Multiping thetas of all nodes of layer 2 with all data instances
Z2 = np.add(Z2,b2) #Broadcasting bais of all nodes of layer 2 

A2 = np.apply_along_axis(vSigmoid, 0, Z2)  # applying sigmoid on each coloumn 



# BACK PROPAGATION

# Layer 2

In [48]:
dz2 = A2 - Y

dw2 = np.dot(dz2,A1.T)/m


db2 = np.sum(dz2,axis = 1) / m



# Layer 1

In [64]:
dg1 = np.multiply((np.apply_along_axis(vSigmoid, 0, Z1)),(1 - np.apply_along_axis(vSigmoid, 0, Z1)))
       
dz1 = np.multiply(np.dot(W2.T,dz2),dg1)

dw1 = np.dot(dz1,X.T)/m
db1 = np.sum(dz1,axis = 1)/m


# UPDATING THETAS

# Layer 1

In [65]:
W1 = W1 - (a * dw1)
b1 = b1 - (a * db1)


# Layer 2

In [66]:
W2 = W2 - (a * dw2)
b2 = b2 - (a * db2)

# Main Function

In [97]:
epoc = 0
epocs = []
gradient = 100
maxGradient1 = 0
maxGradient2 = 0
errors = []

while gradient > 0.01:  # and gradient > 0.01 epoc < 200 and 
    #=========================OUTPUT OF LAYER 0 ============================
    #Layer 0 contains our features

    A0 = X


    #Number of Nodes 9
    #Input of layer 1 is A0 (Output of layer 0)

    W1 = np.random.rand(2,2)
    b1 = np.random.rand(2,1)


    Z1 = np.dot(W1,A0) #Multiping thetas of all nodes of layer 1 with all data instances
    Z1 = np.add(Z1,b1) #Broadcasting bais of all nodes of layer 1 

    A1 = np.apply_along_axis(vSigmoid, 0, Z1)  # applying sigmoid on each coloumn 

    # Number of Nodes 1
    #Input of layer 2 is A1 (Output of layer 1)

    W2 = np.random.rand(1,2)
    b2 = np.random.rand()

    Z2 = np.dot(W2,A1) #Multiping thetas of all nodes of layer 2 with all data instances
    Z2 = np.add(Z2,b2) #Broadcasting bais of all nodes of layer 2 

    A2 = np.apply_along_axis(vSigmoid, 0, Z2)  # applying sigmoid on each coloumn 
    
    errors.append(error(Y,A2))
    print("epoc : "+ str(epoc))
    #print(errors[epoc])
    #BackPropagation
    #Layer 2
    dz2 = A2 - Y

    dw2 = np.dot(dz2,A1.T)/m

    db2 = np.sum(dz2,axis = 1) / m
    
    #Layer 1
    dg1 = np.multiply((np.apply_along_axis(vSigmoid, 0, Z1)),(1 - np.apply_along_axis(vSigmoid, 0, Z1)))
       
    dz1 = np.multiply(np.dot(W2.T,dz2),dg1)

    dw1 = np.dot(dz1,X.T)/m
    db1 = np.sum(dz1,axis = 1)/m

    #UPDATING THETAS
    #layer 1
    W1 = W1 - (a * dw1)
    b1 = b1 - (a * db1)
    
    #layer 2
    W2 = W2 - (a * dw2)
    b2 = b2 - (a * db2)

    #finding max gradient in both layers
    
    maxGradient1 = np.amax(dw1)
    maxGradient2 = np.amax(dw2)
    gradient = min([maxGradient1,maxGradient2])
    print("gradient: " +  str(gradient))
    epoc = epoc + 1
    epocs.append(epoc)
    

# plt.figure(num=None, figsize=(12, 9), dpi=80)
# plt.plot(epocs, errors,'-bo')
# plt.title("Training Error wrt epoc")
# plt.xlabel("Errors")
# plt.ylabel("Epocs")
# plt.yticks(errors)
# plt.show()
print("ERRORS")
print(errors)    

print("FINAL WEIGHTS LAYER 1")
print(W1)

print("FINAL BIAS LAYER 1")
print(b1)

print("FINAL WEIGHTS LAYER 2")
print(W2)

print("FINAL BIAS LAYER 2")
print(b2)

epoc : 0
gradient: 0.012440763118155104
epoc : 1
gradient: 0.011979015401975336
epoc : 2
gradient: 0.0192625137138481
epoc : 3
gradient: 0.007043061054146147
ERRORS
[0.4580330159879369, 0.36814445407827123, 0.5064436679786711, 0.33312058063675043]
FINAL WEIGHTS LAYER 1
[[0.87415832 0.40053068]
 [0.48885052 0.21869788]]
FINAL BIAS LAYER 1
[[0.43517977]
 [0.38083014]]
FINAL WEIGHTS LAYER 2
[[0.21118307 0.41775526]]
FINAL BIAS LAYER 2
[[0.34757969]]
